### ISSUE TITLE
ERROR: This plugin was built with an older plugin structure.

### ISSUE THREAD

**Issue by cbmurphy** [wikimedia/search-extra#3]
When trying to install on Elasticsearch 6.3.2 (using the plugin for 6.3.1), I get the following error message:

Warning: sha512 not found, falling back to sha1. This behavior is deprecated and will be removed in a future release. Please update the plugin to use a sha512 checksum.
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

**Comment by nomoa** [comment]
Thanks for the report, I'll fix the zip layout and try to add sha-512.
Unfortunately I don't think you can use the 6.3.1.1 version of the plugin on elastic 6.3.2, I'll have to release a version for it.

**Comment by nguyenminhduc9988** [comment]
Have you solve this problem yet, I am using Elasticsearch 6.3.1 and I really need this plugin to import the wikipedia index. Please

**Comment by wileeam** [comment]
Hello,
just found out about this as I got the same problem...
Do you have any update @nomoa ?

**Comment by nomoa** [comment]
Sorry for the late reply, I'm out til next monday. FYI the fix is currently under review here https://gerrit.wikimedia.org/r/c/search/extra/+/450230
Hopefully I'll be able to ship a new release next monday.
In the meantime (as a workaround) you can extract the [current zip](https://repo1.maven.org/maven2/org/wikimedia/search/extra/6.3.1.1/extra-6.3.1.1.zip) file and install the plugin manually by extracting and copying all files under `elasticsearch` to `/usr/share/elasticsearch/plugins/extra`.

**Comment by nomoa** [comment]
Please install the 6.3.1.2 version of the plugin, it should still complain about the SHA (will be fixed properly in the next release) but the zip layout should be correct.

**Comment by lasagar** [comment]
Do you have it version 6.4. I am getting ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.
